"""Build the podcast RSS feed with feedgen from a list of episodes.

Each episode is a dict: {url, title, date (YYYY-MM-DD), length (bytes, optional),
duration (seconds, optional)}. pubDate is derived from the date at a fixed local
time so feeds are stable.
"""
import logging
from datetime import UTC, datetime, time

log = logging.getLogger(__name__)

PUBLISH_LOCAL_TIME = time(7, 0)  # episodes are "released" at 07:00 local


def _zone(tz_name: str):
    try:
        from zoneinfo import ZoneInfo
        return ZoneInfo(tz_name)
    except Exception:
        log.warning("timezone %r unavailable (need tzdata?); using UTC", tz_name)
        return UTC


def build_feed(title: str, base_url: str, feed_url: str,
               episodes: list[dict], cover_url: str | None = None,
               author: str = "The Walking Dev",
               owner_email: str = "",
               category: str = "Technology",
               language: str = "fr",
               description: str | None = None,
               tz_name: str = "Europe/Paris") -> bytes:
    from feedgen.feed import FeedGenerator

    tz = _zone(tz_name)
    fg = FeedGenerator()
    fg.load_extension("podcast")
    fg.title(title)
    fg.link(href=base_url, rel="alternate")
    fg.link(href=feed_url, rel="self")
    fg.description(description or f"Daily audio brief generated by {author}.")
    fg.language(language)
    # iTunes/Apple Podcasts metadata (required for a valid podcast channel).
    fg.podcast.itunes_author(author)
    fg.podcast.itunes_explicit("no")
    fg.podcast.itunes_category(category)
    if owner_email:
        fg.podcast.itunes_owner(name=author, email=owner_email)
    if cover_url:
        fg.podcast.itunes_image(cover_url)
        fg.image(url=cover_url, title=title, link=base_url)
    # feedgen's add_entry() prepends, so add oldest-first to get newest-first XML.
    for ep in reversed(episodes):
        fe = fg.add_entry()
        fe.id(ep["url"])
        fe.title(ep["title"])
        fe.enclosure(ep["url"], str(ep.get("length", 0)), "audio/mpeg")
        fe.pubDate(_pubdate(ep["date"], tz))
        dur = ep.get("duration")
        if dur:
            fe.podcast.itunes_duration(_hms(int(dur)))
    return fg.rss_str(pretty=True)


def _pubdate(date_str: str, tz) -> datetime:
    y, m, d = (int(x) for x in date_str.split("-"))
    return datetime.combine(datetime(y, m, d), PUBLISH_LOCAL_TIME, tzinfo=tz)


def _hms(seconds: int) -> str:
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:d}:{m:02d}:{s:02d}" if h else f"{m:d}:{s:02d}"
